name: Publish to NPM with Random Version

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Generate random version
      run: |
        RANDOM_SUFFIX=$(date +%s)
        PACKAGE_VERSION=$(node -p "require('./package.json').version")-beta.$RANDOM_SUFFIX
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

    - name: Update version in package.json
      run: |
        npm version ${{ env.PACKAGE_VERSION }} --no-git-tag-version

    - name: Build
      run: npm run build

    - name: Publish to npm with beta tag
      run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
